os: linux
dist: bionic
arch:
  - ppc64le
  - amd64

sudo: required

language: c

services:
  - docker

env:
  global:
    - GITHUB_REPO=pmem/pmdk
    - DOCKERHUB_REPO=pmem/pmdk
    - OS=ubuntu
    - OS_VER=19.10
    - MAKE_PKG=0
    - PMDK_CC=gcc
    - PMDK_CXX=g++
    - REMOTE_TESTS=1
    - VALGRIND=1
    - ppc64le__BLACKLIST_FILE=../../utils/docker/ppc64le.blacklist
  matrix:
    - COVERAGE=1 FAULT_INJECTION=1 TEST_BUILD=debug

# XXX: The jobs which are explicitly included inherit the first value of the
# expansion keys defined. In this case the only expansion key with more than
# one entry is the `arch:` key, and that is why ppc64le is first, to save some
# space here and not have to define `arch:` for each entry.
matrix:
  include:
    - env: FAULT_INJECTION=1 TEST_BUILD=debug
    - env: FAULT_INJECTION=1 TEST_BUILD=nondebug
    - env: PMDK_CC=clang PMDK_CXX=clang++ TEST_BUILD=debug
    - env: PMDK_CC=clang PMDK_CXX=clang++ TEST_BUILD=nondebug
    - env: OS=fedora OS_VER=31 PMDK_CC=clang PMDK_CXX=clang++ TEST_BUILD=debug
    - env: OS=fedora OS_VER=31 PMDK_CC=clang PMDK_CXX=clang++ TEST_BUILD=nondebug AUTO_DOC_UPDATE=1
    - env: MAKE_PKG=1 EXPERIMENTAL=y REMOTE_TESTS=0 VALGRIND=0 NDCTL_ENABLE=n PUSH_IMAGE=1
    - env: MAKE_PKG=1 EXPERIMENTAL=y REMOTE_TESTS=0 VALGRIND=0 PUSH_IMAGE=1 OS=fedora OS_VER=31
    - env: MAKE_PKG=1 EXPERIMENTAL=y REMOTE_TESTS=0 VALGRIND=0 NDCTL_ENABLE=n PMDK_CC=clang PMDK_CXX=clang++
    - env: COVERITY=1

before_install:
  - eval export "$(export -p | sed -n "s/^declare -x ${TRAVIS_CPU_ARCH}__//p")"
  - echo $TRAVIS_COMMIT_RANGE
  - export HOST_WORKDIR=`pwd`
  - cd utils/docker
  - ./pull-or-rebuild-image.sh

script:
  - ./build-travis.sh

after_success:
  - source ./set-vars.sh
  - if [[ -f $CI_FILE_PUSH_IMAGE_TO_REPO ]]; then ./images/push-image.sh; fi
